TwiX 1 project initial setup
iOS-vk-education/2024_1_Envelope pull request #1
Opened 2024-10-17 16:54 UTC by 999ashu

Created base .gitignore and default ios app project

2024-10-17 17:04 UTC, oooooorg approved these changes
Good job, Andrew!

2024-10-17 17:12 UTC, UlinEgor approved these changes

2024-10-17 17:12 UTC, UlinEgor approved these changes

2024-10-17 17:17 UTC, alwh1te approved these changes
Awesome

2024-10-17 17:47 UTC, alwh1te approved these changes
Second try

2024-10-17 18:02 UTC, MX126 requested changes

2024-10-17 18:02 UTC, MX126 commented on .gitignore
> +xcuserdata
https://www.toptal.com/developers/gitignore

я бы посмотрел, что еще можно сюда добавить, потому что есть еще DerivedData/ и прочая лабуда

2024-10-26 12:20 UTC, MX126 approved these changes

2024-10-26 12:26 UTC, merged