Feed View
iOS-vk-education/2024_1_Envelope pull request #11
Opened 2024-12-02 14:51 UTC by alwh1te

Feed view, Main feed screen, integration of feed into profile screen

2024-12-04 18:49 UTC, oooooorg approved these changes

2024-12-08 15:58 UTC, UlinEgor approved these changes

2024-12-08 16:00 UTC, oooooorg approved these changes

2024-12-10 21:53 UTC, 999ashu approved these changes

2024-12-10 22:03 UTC, MX126 commented on TwiX/Feed/Controller/MainFeedViewController.swift
> +class MainFeedViewController : UIViewController {
не хватает final

2024-12-10 22:15 UTC, MX126 requested changes

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/Controller/MainFeedViewController.swift
> +
лишний отступ

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/Controller/MainFeedViewController.swift
> +    }
затерялся среди private

вынеси методы private как extension или пометь их марком в одну кучу

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/Controller/MainFeedViewController.swift
> +        ])
Констреинты создаются в функции для создания констреинтов
Функция должна делать то, как она называется, это можно вынести

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/Controller/MainFeedViewController.swift
> +    }
почему селектор не повесил на кнопку?

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/Controller/PostViewController.swift
> +
лишний отступ

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/Services/PostManager.swift
> +    func fetchPosts(completion: @escaping ([Post]) -> Void) {
Посмотри, что будет с приложением при выключенном интернете, стоит подумать над окном, показывающим это

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/View/FeedView.swift
> +//        cell.tintColor = self.tintColor
коммент нужен?

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/View/FeedView.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: String(describing: PostTableViewCell.self), for: indexPath) as! PostTableViewCell
as! - плохо, используй as? и не поймаешь краш :)

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/View/PostView.swift
> +            guard let data = data else { return }
объедини giard'ы

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/View/PostView.swift
> +        let task = URLSession.shared.dataTask(with: post.authorAvatarURL) { [weak self] data, response, error in
не вижу обработки ошибок

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/View/PostView.swift
> +        commentsCountLabel.textColor = .gray
очень много повторяющихся сетапов

```
for element in [authorLabel, usernameLabel, timeLabel и т.п] {
       element.font = UIFont(name: Fonts.Urbanist_Regular, size: 16)
       element.textColor = ...
}
```

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/View/PostView.swift
> +            }
а сверху что?

2024-12-10 22:15 UTC, MX126 commented on TwiX/Navigation/Controller/CreatePostController.swift
> +
лишние отступы

2024-12-10 22:15 UTC, MX126 commented on TwiX/Navigation/Controller/CreatePostController.swift
> +class CreatePostController: UIViewController {
нет final

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/View/PostView.swift
> +class PostView: UIView {
нет final

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/View/PostTableViewCell.swift
> +class PostTableViewCell: UITableViewCell {
нет final

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/View/FeedView.swift
> +class FeedView : UIView {
нет final

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/Services/PostManager.swift
> +class PostManager {
нет final

2024-12-10 22:15 UTC, MX126 commented on TwiX/Feed/Controller/PostViewController.swift
> +class PostViewController: UIViewController {
нет final

2024-12-10 22:15 UTC, MX126 commented on TwiX/Navigation/Controller/TabBarController.swift
> +class TabBarController: UITabBarController {
нет final

2024-12-10 22:15 UTC, MX126 commented on TwiX/Navigation/Controller/TabBarController.swift
> +        let mainFeedVC = createNav(title: "", image: UIImage(named: Strings.Icons.mainFeedTabBarIcon), vc: MainFeedViewController())
createNavItem

2024-12-10 22:47 UTC, alwh1te commented on TwiX/Feed/Controller/MainFeedViewController.swift
> +
solved

2024-12-10 22:48 UTC, alwh1te commented on TwiX/Feed/Controller/MainFeedViewController.swift
> +class MainFeedViewController : UIViewController {
solved

2024-12-10 22:49 UTC, alwh1te commented on TwiX/Feed/Controller/PostViewController.swift
> +class PostViewController: UIViewController {
solved

2024-12-10 22:52 UTC, alwh1te commented on TwiX/Feed/View/FeedView.swift
> +class FeedView : UIView {
solved

2024-12-10 22:52 UTC, alwh1te commented on TwiX/Feed/View/PostTableViewCell.swift
> +class PostTableViewCell: UITableViewCell {
solved

2024-12-10 22:55 UTC, alwh1te commented on TwiX/Navigation/Controller/TabBarController.swift
> +class TabBarController: UITabBarController {
solved

2024-12-10 22:56 UTC, alwh1te commented on TwiX/Feed/View/FeedView.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: String(describing: PostTableViewCell.self), for: indexPath) as! PostTableViewCell
solved

2024-12-10 23:05 UTC, alwh1te commented on TwiX/Feed/View/PostView.swift
> +            }
Вынес общий код, а почистить забыл

2024-12-10 23:05 UTC, alwh1te commented on TwiX/Feed/View/PostView.swift
> +class PostView: UIView {
solved

2024-12-10 23:06 UTC, alwh1te commented on TwiX/Feed/View/FeedView.swift
> +//        cell.tintColor = self.tintColor
solved

2024-12-10 23:06 UTC, alwh1te commented on TwiX/Feed/Services/PostManager.swift
> +class PostManager {
solved

2024-12-10 23:07 UTC, alwh1te commented on TwiX/Feed/Controller/MainFeedViewController.swift
> +        ])
solved

2024-12-10 23:07 UTC, alwh1te commented on TwiX/Navigation/Controller/CreatePostController.swift
> +class CreatePostController: UIViewController {
solved

2024-12-10 23:07 UTC, alwh1te commented on TwiX/Navigation/Controller/CreatePostController.swift
> +
solved

2024-12-11 19:51 UTC, MX126 approved these changes

2024-12-11 19:51 UTC, MX126 commented on TwiX/Feed/Controller/MainFeedViewController.swift
> +
лишний отступ

2024-12-12 12:52 UTC, alwh1te commented on TwiX/Feed/Controller/MainFeedViewController.swift
> +    }
не понял замечание

2024-12-13 10:12 UTC, merged