resolved conversations
iOS-vk-education/2024_1_Envelope pull request #17
Opened 2024-12-17 19:44 UTC by alwh1te

2024-12-18 15:28 UTC, UlinEgor approved these changes

2024-12-18 15:28 UTC, oooooorg approved these changes

2024-12-19 20:40 UTC, 999ashu requested changes

2024-12-19 20:40 UTC, 999ashu commented on TwiX.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 17.6;
well well well

2024-12-19 20:40 UTC, 999ashu commented on TwiX.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 17.6;
well well well

2024-12-19 20:46 UTC, 999ashu approved these changes

2024-12-22 18:55 UTC, MX126 approved these changes

2024-12-23 09:10 UTC, merged