Untitled Pull Request
iOS-vk-education/2024_1_Envelope pull request #4
Opened 2024-11-17 16:12 UTC by alwh1te

Сверстал флоу авторизации, сначала верстал на storyboard, но было принято решение мигрировать на swiftUI (для лучшей интеграцией с бд, ну и для опыта)
Сделано три экрана, пока без бекенда

2024-11-17 18:34 UTC, MX126 requested changes
Хорошая работа!


Проекту не хватает структуры. Например, шрифты, ассеты и Launchscreen можно перенести в общую папку Resources.

Не понял следующих моментов: что за пустая кнопка при запуске, которая кидает на авторизацию? ЧТо будет вместо нее?

Нет файлов с локализацией

При тапе на Sign up кидает на логин, sign in в принципе не кликабельный


Подправь все эти моменты и тогда можно будет говорить, что этот мр - это верстка без бека.

2024-11-17 18:34 UTC, MX126 commented on TwiX/Authentication/Authentication.storyboard
Удалить, так как решили перейти на нативную верстку

2024-11-17 18:34 UTC, MX126 commented on TwiX/Authentication/AuthenticationFlow.swift
Все числовые значения, явно заданные строки вынести в extension. Реализовать в enum или struct Constants. Такой extension для каждой вьюшки и других экранов

2024-11-17 18:34 UTC, MX126 commented on TwiX/Authentication/AuthenticationFlow.swift
где-то есть отступы между property wrappers, где-то нет. Решите, какому стилю будете придерживаться

2024-11-17 18:34 UTC, MX126 commented on TwiX/Authentication/AuthenticationFlow.swift
> +struct AbstractBigButton: View {
Не самое лучшее название, нужно что-то осмысленное

2024-11-17 18:34 UTC, MX126 commented on TwiX/Authentication/AuthenticationFlow.swift
> +struct AbstractSmallButton: View {
Аналогично с предыдущим названием

2024-11-17 18:34 UTC, MX126 commented on TwiX/Authentication/IntroViewController.swift
Этот файл нужен?

2024-11-17 18:34 UTC, MX126 commented on TwiX/Authentication/LoginViewController.swift
Код для влития в main должен приходить без закомментированных строк

2024-11-17 18:34 UTC, MX126 commented on TwiX/Authentication/NavBarView.swift
не хватает `MARK: -` для разделения логики файла

2024-11-17 18:34 UTC, MX126 commented on TwiX/Authentication/RegisterViewController.swift
пустой Вьюконтроллер, да еще и с комментариями)

2024-11-18 11:25 UTC, alwh1te commented on TwiX/Authentication/AuthenticationFlow.swift
> +struct AbstractBigButton: View {
fixed

2024-11-18 11:27 UTC, alwh1te commented on TwiX/Authentication/AuthenticationFlow.swift
> +struct AbstractSmallButton: View {
fixed

2024-11-18 11:30 UTC, alwh1te commented on TwiX/Authentication/AuthenticationFlow.swift
fixed

2024-11-18 11:40 UTC, alwh1te commented on TwiX/Authentication/AuthenticationFlow.swift
вроде fixed

2024-11-20 15:22 UTC, UlinEgor approved these changes

2024-11-20 15:34 UTC, oooooorg approved these changes

2024-11-21 18:11 UTC, UlinEgor approved these changes

2024-11-21 21:40 UTC, 999ashu approved these changes

2024-11-22 14:12 UTC, MX126 approved these changes

2024-11-22 14:31 UTC, merged