Add settings screen
iOS-vk-education/2024_1_Envelope pull request #7
Opened 2024-11-23 22:37 UTC by UlinEgor

Пока кнопки не рабочие (но тыкаются)

2024-11-25 11:29 UTC, alwh1te approved these changes

2024-11-28 15:40 UTC, oooooorg approved these changes

2024-11-28 15:40 UTC, 999ashu approved these changes

2024-12-01 15:06 UTC, MX126 requested changes

2024-12-01 15:06 UTC, MX126 commented on TwiX/Settings/SettingsScreenController.swift
> +fileprivate func generateImage(imageName: String, width: CGFloat, height: CGFloat) -> UIImageView {
почему был выбран fileprivate?

2024-12-01 15:06 UTC, MX126 commented on TwiX/Settings/SettingsScreenController.swift
> +        NSLayoutConstraint.activate([
Все констреинты вынести в один метод, аналогично предыдущему  pr

2024-12-14 22:31 UTC, closed without merging